Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,21 +38,22 @@ jobs:
       - name: conditioncheck
         run: |
               awk -F "," 'NR>1{print $8}' sanity/result.jtl >> abc.txt
-              TEXT=`cat abc.txt | grep true | wc -l`
+              TEXT=`cat abc.txt | grep false | wc -l`
               echo "This is $TEXT" 
               if [ ${TEXT} > 1 ]; then
               {
-                 echo "Sanity Pass"
-                 echo "::set-output name=run_job_b::yes"
+                 echo "Sanity Failed"
+                 echo "::set-output name=run_job_a::no"
+                 exit 1
               }
               else
               {
-                echo "Sanity Failed"
-                exit 1
+                echo "Sanity Pass"
+                cho "::set-output name=run_job_a::yes"
               }
               fi
     outputs:
-      run_job_b: ${{ steps.set.outputs.run_job_b }}
+      run_job_b: ${{ steps.set.outputs.run_job_a }}
 
   b:
      name: b
@@ -147,4 +148,4 @@ jobs:
           # Optional nodemailerlog: true/false
           #nodemailerlog: false
           # Optional nodemailerdebug: true/false if true lognodem will also be set true
-          #nodemailerdebug: false   
+          #nodemailerdebug: false
